### ISSUE TITLE
Convert to v2 addon?

### ISSUE THREAD

**Issue by NullVoxPopuli** [qonto/ember-autofocus-modifier#353]
I can do this, but I'm wondering how much you want it broken up.

All at once:
 - bigger PR
 - easier to see how all the pieces fit together
 - easier for undermaintain repos, imo
 
Split in to many PRs:
 - smaller PRs
 - easier to review for maintained repos
 - harder to see how all the pieces fit together
 
 The process (regardless of the number of PRs):
 - change to monorepo + update CI
 - move tests to a test-app + delete the dummy app + update CI
 - convert the addon to v2 + update CI
 
 _because ember-auto-import@v2 is presently not a in `dependencies`, this is be a breaking change_

**Comment by mrloop** [comment]
A single PR with a few commits splitting up the work would be great. What do you think @aoumiri?

**Comment by aoumiri** [comment]
Indeed! A single PR with multiple commits would be appreciated 👍
