### ISSUE TITLE
Ember Animated {{animated-if}}

### ISSUE THREAD

**Issue by evoactivity** [qonto/ember-autofocus-modifier#88]
With a normal if the first and second input will be focused as the `this.something` variable is changed
```hbs
{{#if this.something}}
  <input {{autofocus}}/>
{{else}}
  <input {{autofocus}}/>
{{/if}}
```
Using an animated-if only the first input will be focused, the second input remains unfocused. This may be an issue with ember-animated but I'm not sure @ef4
```hbs
{{#animated-if this.something use=this.transition}}
  <input {{autofocus}}/>
{{else}}
  <input {{autofocus}}/>
{{/animated-if}}
```

**Comment by ef4** [comment]
To make this work seamlessly, we'd need to create a protocol in ember-animated that autofocus could use -- but only when ember-animated is present in the app -- that would let it find out when the enclosing animation is done.

**Comment by aoumiri** [comment]
Hum, I'm not a big expert of ember animated. Could you give an example project where this issue can be reproduced ?
Thanks!
